name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile with .NET Framework 4.x csc
      shell: cmd
      run: |
        "%windir%\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /reference:System.Management.dll /target:exe /out:activate.exe activate.cs

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kms-activator
        path: activate.exe
